First Draft of Lotame Panorama ID Documentation
Lotame/prebid.github.io pull request #1
Opened 2020-06-03 13:41 UTC by markaconrad

2020-06-03 18:48 UTC, ErikMHummel requested changes
We should probably get some marketing speak from Charlie and then we can tone it down a little to match the other company's sections.

2020-06-03 18:48 UTC, ErikMHummel commented on dev-docs/modules/userId.md
> +| name | Required | String | May be: `"britepoolId"`, `"criteo"`, `"digitrust"`, `"id5id"`, `identityLink`, `"liveIntentId"`,`"lotamePanoramaId"` `"parrableId"`, `"netId"`, `"pubCommonId"`,  or `"uni
Needs a comma.

2020-06-03 18:48 UTC, ErikMHummel commented on dev-docs/modules/userId.md
> +* **Lotame Panorama ID** - a user ID that does not depend on 3rd party cookies provided by Lotame.
Do we want to mention it is a unique individual across devices? Not sure how much marketing speak to put here. But looking at others, they seems to use it pretty heavily.

2020-06-03 18:48 UTC, ErikMHummel commented on dev-docs/modules/userId.md
> +The Lotame Panorama ID module enables publishers to exchange data with the ad tech ecosystem without depending on 3rd party cookies.
Do we want to link to https://www.lotame.com/panorama/ or https://www.lotame.com? 

Maybe a follow-on sentence of:

> For more information, please see the [Lotame Panorama](https://www.lotame.com/panorama/) product site.

2020-06-04 20:05 UTC, markaconrad commented on dev-docs/modules/userId.md
> +| name | Required | String | May be: `"britepoolId"`, `"criteo"`, `"digitrust"`, `"id5id"`, `identityLink`, `"liveIntentId"`,`"lotamePanoramaId"` `"parrableId"`, `"netId"`, `"pubCommonId"`,  or `"uni
Fixed

2020-06-04 20:05 UTC, markaconrad commented on dev-docs/modules/userId.md
> +The Lotame Panorama ID module enables publishers to exchange data with the ad tech ecosystem without depending on 3rd party cookies.
Updated with wording from Charlie

2020-06-04 20:05 UTC, markaconrad commented on dev-docs/modules/userId.md
> +* **Lotame Panorama ID** - a user ID that does not depend on 3rd party cookies provided by Lotame.
Updated with wording from Charlie

2020-06-04 20:14 UTC, ErikMHummel approved these changes
I'm good now Mark.

2021-01-13 14:09 UTC, closed without merging